### PR TITLE
Engage climber

### PR DESCRIPTION
**Pull request by treecal20**

### CODE REVIEW

**Comment by open-sourceress** [comment]
Hi Calvin! It looks like your `isFinished` method mentions an OI method that doesn't exist. Please remove it and simply `return false` for now.

**Comment by treecal20** [comment]
It should be fixed

**Comment by open-sourceress** [comment]
Hi Calvin! Instead of creating a motor in the command, please reference the subsystem in the robot class.

**Comment by treecal20** [comment]
It is fixed

**Comment by open-sourceress** [comment]
Hi Calvin! In your test comment you mention that you "expect to turn at half speed." What is turning at half speed? Finally, please remove the `// TODO` comments and we should be all set.

**Comment by open-sourceress** [comment]
Thanks Calvin!

**Pull request merged**
