### PR TITLE
Drive Base

### PR DESCRIPTION
**Pull request by treecal20**

### CODE REVIEW

**Comment by treecal20** [comment]
Drive Base and some Autonomous

**Comment by treecal20** [comment]
Drive Base and some Autonomous

**Comment by open-sourceress** [comment]
Hi Calvin! For the sake of organization, I'd appreciate it if you could split this into separate pull requests for separate components.

For this one, please create a new branch from the `master` branch of this repository, and copy just the `DriveBase` changes. Everything else will be handled per-item, so that this repository is always stable and complete.

It appears you have some merge conflicts in your files. See `DriveBase.java` lines 43-82. These should prevent the code from compiling, which is a basic requirement before I can merge your changes. Also, it appears you have overwritten the changes that Matthew made - namely the Hopper - which is why I recommend you create a new branch from this repository to work on. That way, you'll have all of Matthew's changes and can add from there.

**Comment by treecal20** [comment]
It should be fixed.

**Comment by open-sourceress** [comment]
Thanks for responding Calvin! This looks like the code from last year, not this year. I recommend you restart from the master branch of this repository to avoid these errors.

**Comment by treecal20** [comment]
Is this better?

**Comment by open-sourceress** [comment]
That's a lot better, but not quite good yet. `Robot.java`, `OI.java`, and `RobotMap.java` still have some stuff not related to driving, and the Move command will be handled as a separate pull request. From there, it looks like just semantic changes.

**Comment by open-sourceress** [comment]
Almost there, Calvin. Thanks for sticking to it this long.  
The extra files are gone, but there's still a bit of extra code. OI should be empty - it's a separate item on the list - and RobotMap should only contain the hopper values (because they were already there) and the values you add for driving. Also, it looks like the Hopper is still deleted from `Robot.java` you can copy the `Robot.java` from this repository and add your changes from there. After that, it should be good to merge!

**Comment by open-sourceress** [comment]
Looks like just one more round left. Moving the drive base will be a separate pull request, so these can be removed for now.  
- `Move.java` can be removed
- `OI.java` can be an empty class
- `RobotMap.LEFT_JOYSTICK` and `RobotMap.RIGHT_JOYSTICK` can be removed

With that, we should be good to merge!

**Comment by treecal20** [comment]
Move is required to use the drive base

**Comment by open-sourceress** [comment]
Not necessarily. Autonomous driving doesn't require the move command, because there'll be a separate command for that. This pull request - the drive base - is just the minimum action required to make the robot move. The logic of feeding values from joysticks is not required for that.

**Comment by treecal20** [comment]
Test is passed

**Comment by treecal20** [comment]
Test is passed x2

**Pull request merged**
