### PR TITLE
Drive/Move Command

### PR DESCRIPTION
**Pull request by treecal20**

### CODE REVIEW

**Comment by open-sourceress** [comment]
Oops! It looks like you added the spit out command to your Move command PR. Once we get Drive done, you can move on to spit out.  
On Move, the joysticks are required but the launchpad is not. Please remove `LAUNCHPAD` from RobotMap and `launchpad` from OI.

**Comment by treecal20** [comment]
It should be fixed

**Comment by open-sourceress** [comment]
If we have 6 drive motors, we'll add them in a separate PR. Go ahead and stick to 2 for now.

**Comment by open-sourceress** [comment]
Looks good Calvin. Thanks!

**Pull request merged**
