### PR TITLE
Operator interface

### PR DESCRIPTION
**Pull request by matthew-oberg**

### CODE REVIEW

**Comment by open-sourceress** [comment]
Hey Matthew! Typically we declare our buttons by what they do, rather than where they are on the joystick. That drastically reduces the number of buttons we need to manage, and makes it easier to move commands from one button to another. You can reference [last year's `OI`](https://github.com/FRC4131/FRCStronghold2016/blob/master/src/org/usfirst/frc/team4131/robot/OI.java) to see what I mean.

**Comment by matthew-oberg** [comment]
Not needed.

**Comment by open-sourceress** [comment]
This is still needed - we do need to map buttons to commands after all. We'll just have one button per command rather than one button per physical button on the joysticks.

**Comment by open-sourceress** [comment]
It looks like you're making the `JoystickButton` fields public. Typically we make the fields private and create public methods to get whether the buttons are pressed (only where necessary).  
Also, please make the joysticks private. (I know you didn't make them public in the first place, but if you're taking on the OI we might as well fix it now.) This will break the `Move` command, so add methods `getLeftSpeed()` and `getRightSpeed()` (to get the y-axis of each joystick) and change `Move` to use them.

**Comment by matthew-oberg** [comment]
I fixed everything you mentioned and tested it.

**Comment by matthew-oberg** [comment]
I added the little comment with the test procedure and date and all of that stuff.

**Pull request merged**
