### PR TITLE
Spit Out

### PR DESCRIPTION
**Pull request by treecal20**

### CODE REVIEW

**Comment by treecal20** [comment]
Spit Out Pull Request started

**Comment by open-sourceress** [comment]
Hi Calvin! Please don't include your changes to OI in this pull request. Because we don't know which buttons will be mapped to which functions, we'll leave it empty for now.

**Comment by treecal20** [comment]
It should be fixed

**Comment by open-sourceress** [comment]
Hi Calvin! it looks like you created the motor in the command, when it should be in the subsystem. Please update this to use `Robot.collector` to run the motors.

**Comment by treecal20** [comment]
Fixed

**Comment by open-sourceress** [comment]
Thanks Calvin!

**Pull request merged**
